export const PERSON = 'PERSON';
export const GET_PERSON_SUCCESS = 'GET_PERSON_SUCCESS';
export const GET_PERSON_FAIL = 'GET_PERSON_FAIL';
export const GET_PERSON_SUCCESS_DELETED = 'GET_PERSON_SUCCESS_DELETED';
export const GET_PERSON_SUCCESS_UPDATED = 'GET_PERSON_SUCCESS_UPDATED';
export const GET_PERSON_SUCCESS_INSERTED = 'GET_PERSON_SUCCESS_INSERTED';